name: macOS

on:
  push:
    branches:
      - 'experiments/githubActionsCI'

jobs:
  macOS_test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: dotnet fsi ./test/test.fsx
