name: windows

on:
  push:
    branches:
      - experiments/githubActionsCI

jobs:
  windows_test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      shell: cmd
      run: dotnet fsi .\test\test.fsx
